version: '3'
services:
  heatmap-provider:
    build:
      ./Heatmap-Provider
    ports:
      - "5000:5000"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - heatmap-provider